name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'img_1.png'
jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: lab1
          POSTGRES_USER: lab
          POSTGRES_PASSWORD: lab
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U lab -d lab1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Export env for Spring (DB & JWT)
        run: |
          echo "DB_URL=jdbc:postgresql://localhost:5432/lab1" >> $GITHUB_ENV
          echo "DB_USER=lab" >> $GITHUB_ENV
          echo "DB_PASS=lab" >> $GITHUB_ENV
          echo "JWT_SIGNING_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Cache Dependency-Check data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: depcheck-${{ runner.os }}-v1

      - name: Build, Test, Security Scans
        run: |
          mvn -B verify org.owasp:dependency-check-maven:check \
            -Dnvd.nist.cveValidForHours=168 \
            -Danalyzer.ossindex.enabled=false

      - name: Upload SpotBugs report (XML)
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-xml
          path: target/spotbugsXml.xml
          if-no-files-found: ignore

      - name: Upload Dependency-Check reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: |
            target/dependency-check-report.html
            target/dependency-check-report.json
            target/dependency-check-report.xml
          if-no-files-found: warn